version: '3'

services:
  web:
    image: php:7.4-apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: mydatabase
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
